<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_1 Off Promo Code</name>
   <tag></tag>
   <elementGuidId>2acdaf85-2427-40bb-b30f-15605cfaa88b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>promotions-modal-checkbox-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>2c9f811461fa932a01620a1e08050dbb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.3.0.0.2.0.0.1.1:0.0.1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1 Off Promo Code</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotions-modal-content&quot;)/div[@class=&quot;promotions-modal-content&quot;]/div[@class=&quot;bx-wrapper&quot;]/div[@class=&quot;bx-viewport&quot;]/ul[@class=&quot;promotions-modal-slider-container&quot;]/li[@class=&quot;pb-height-100 promotions-modal-slider-content&quot;]/div[@class=&quot;promotions-modal-promotions-container&quot;]/div[@class=&quot;promotions-checkbox-list&quot;]/div[@class=&quot;promotions-checkbox-list-element promo-promotion&quot;]/label[@class=&quot;promotions-modal-checkbox-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
