<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete Address 2</name>
   <tag></tag>
   <elementGuidId>1c93d24c-7160-4ef9-9c2a-e68c20090267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;address-book-container&quot;)/div[@class=&quot;address-book-content settings-content grid-parent grid-100 tablet-grid-100 mobile-grid-100&quot;]/table[1]/tbody[2]/tr[2]/td[3]/a[@class=&quot;delete-address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete-address</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.1.0.2.1.1.0.1.1.2.1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-book-container&quot;)/div[@class=&quot;address-book-content settings-content grid-parent grid-100 tablet-grid-100 mobile-grid-100&quot;]/table[1]/tbody[2]/tr[2]/td[3]/a[@class=&quot;delete-address&quot;]</value>
   </webElementProperties>
</WebElementEntity>
