<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save Password Window</name>
   <tag></tag>
   <elementGuidId>e4b245a5-26c2-4312-ab93-f34af8b7a6ee</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>change-password-modal-save grid-parent prefix-25 tablet-prefix-25 mobile-prefix-5 grid-50 tablet-grid-50 mobile-grid-90</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.1.0.2.0.2.1.0.4.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;change-password-modal&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;personal-settings-container&quot;]/div[@class=&quot;grid-parent grid-100 tablet-grid-100 mobile-grid-100 pb-center&quot;]/button[@class=&quot;change-password-modal-save grid-parent prefix-25 tablet-prefix-25 mobile-prefix-5 grid-50 tablet-grid-50 mobile-grid-90&quot;]</value>
   </webElementProperties>
</WebElementEntity>
