<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Email-XPATH</name>
   <tag></tag>
   <elementGuidId>d1f4d151-1732-467a-bfc5-976747f36ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;personal-settings-container&quot;]/div[2]/div[3]/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;personal-settings-container&quot;)/div[@class=&quot;personal-settings-content settings-content grid-parent grid-100 tablet-grid-100 mobile-grid-100&quot;]/div[@class=&quot;personal-details-row grid-100 tablet-grid-100 mobile-grid-100 grid-parent&quot;]/span[@class=&quot;personal-details-content grid-parent grid-80 tablet-grid-80 mobile-grid-70&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>personal-details-content grid-parent grid-80 tablet-grid-80 mobile-grid-70</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.1.0.2.0.1.2.1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal-settings-container&quot;)/div[@class=&quot;personal-settings-content settings-content grid-parent grid-100 tablet-grid-100 mobile-grid-100&quot;]/div[@class=&quot;personal-details-row grid-100 tablet-grid-100 mobile-grid-100 grid-parent&quot;]/span[@class=&quot;personal-details-content grid-parent grid-80 tablet-grid-80 mobile-grid-70&quot;]</value>
   </webElementProperties>
</WebElementEntity>
