<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PhoneNumber-XPATH</name>
   <tag></tag>
   <elementGuidId>2d7a039f-65ab-4fc7-9fac-8f20ff6ff79e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;personal-settings-container&quot;]/div[2]/div[5]/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[count(. | //*[text() = '91111111']) = count(//*[text() = '91111111'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>personal-details-content grid-parent grid-80 tablet-grid-80 mobile-grid-70</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.1.0.2.0.1.4.1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>91111111</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal-settings-container&quot;)/div[@class=&quot;personal-settings-content settings-content grid-parent grid-100 tablet-grid-100 mobile-grid-100&quot;]/div[@class=&quot;personal-details-row grid-100 tablet-grid-100 mobile-grid-100 grid-parent&quot;]/span[@class=&quot;personal-details-content grid-parent grid-80 tablet-grid-80 mobile-grid-70&quot;]</value>
   </webElementProperties>
</WebElementEntity>
