<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password-XPATH</name>
   <tag></tag>
   <elementGuidId>78952a95-ebcd-46b8-ac87-94173212b8ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@type = 'password']) = count(//*[@type = 'password'])][count(. | //*[@placeholder = 'Password']) = count(//*[@placeholder = 'Password'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;signin-flow-modal&quot;]/div[6]/div[1]/div[2]/div[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.4.5.0.1.3.0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-flow-modal&quot;)/div[@class=&quot;pickup-store-content&quot;]/div[@class=&quot;grid-100 tablet-grid-100 mobile-grid-100 grid-parent signin-flow-content guest&quot;]/div[@class=&quot;sign-up-container&quot;]/div[@class=&quot;grid-parent grid-100 tablet-grid-100 mobile-grid-100&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
